LinkCapital.Portal/Web/ViewModels/LoanCenter/CurrentLoanViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Web.ViewModels.LoanCenter
{
    public class CurrentLoanViewModel
    {
        [Display(Name = "Loan Number")]
        public long LoanId { get; set; }
        [Display(Name = "Loan Disbursement Date")]
        public DateTime? DisbursementDate { get; set; }
        [Display(Name = "Loan Type")]
        public string LoanType { get; set; }
        [Display(Name = "Loan Status")]
        public string LoanStatus { get; set; }
         
        [Display(Name = "Original Balance")]
        public decimal OriginalBalance { get; set; }
        [Display(Name = "Late Fees")]
        public decimal LateFees { get; set; }
        [Display(Name = "Current Balance")]
        public decimal CurrentBalance { get; set; }

        [Display(Name = "Monthly Payment")]
        public decimal MonthlyPayment { get; set; }
        
        [Display(Name = "Next Due Date")]
        public DateTime? NextDueDate { get; set; }
        [Display(Name = "Days Delinquent")]
        public long DaysDelinquent { get; set; }
        [Display(Name = "Amount Past Due")]
        public decimal PastDueAmount { get; set; }

        [Display(Name = "Interest Rate")]
        public decimal InterestRate { get; set; }
        
        [Display(Name = "Accurate As Of")]
        public DateTime? DateCalculated { get; set; }
    }
}

LinkCapital.Portal/Web/ViewModels/LoanCenter/LoanApplicationViewModel.cs
namespace Web.ViewModels.LoanCenter
{
    public class LoanApplicationViewModel
    {
        public string HttpMethod { get; set; }
        public string Url { get; set; }
        public string Payload { get; set; }
    }
}

LinkCapital.Portal/Web/ViewModels/LoanCenter/LoanInformationViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Web.ViewModels.LoanCenter
{
    public class LoanInformationViewModel
    {
        [Required]
        [Display(Name = "State of Permanent Residence")]
        public string StateOfResidence { get; set; }
        [Required]
        [Display(Name = "Loan Balance")]
        public decimal LoanAmount { get; set; }
        [Required(ErrorMessage = "You must answer the question.")]
        [Display(Name="Residency Status")]
        public bool? IsMedicalResident { get; set; }
    }
}

LinkCapital.Portal/Web/ViewModels/LoanCenter/ManageLoanViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Web.ViewModels.LoanCenter
{
    public class ManageLoanViewModel
    {
        public string HttpMethod { get; set; }
        public string Url { get; set; }
        public string Payload { get; set; }
    }
}

LinkCapital.Portal/Web/Controllers/LoanCenterController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using Web.EntityModels;
using Web.Services;
using Web.Services.Interfaces;
using Web.Utilities;
using Web.ViewModels.LoanCenter;
using ApplicationUser = Web.EntityModels.ApplicationUser;
using DataContext = Web.Repositories.DataContext;

namespace Web.Controllers
{
    [Authorize]
    public class LoanCenterController : Controller
    {
        public LoanCenterController()
            : this(new UserManager(new UserStore<ApplicationUser>(new DataContext())), new LoanCenterService(), new LoanProgramService(), new StateService(), new LoanSubmissionService())
        {
        }

        public LoanCenterController(UserManager userManager, ILoanCenterService loanCenterService, ILoanProgramService loanProgramService, IStateService stateService, ILoanSubmissionService loanSubmissionService)
        {
            UserManager = userManager;
            UserManager.UserValidator = new UserValidator<ApplicationUser>(UserManager) { AllowOnlyAlphanumericUserNames = false };

			LoanCenterService = loanCenterService;
			LoanProgramService = loanProgramService;
			StateService = stateService;
            LoanSubmissionService = loanSubmissionService;
        }

        public UserManager UserManager { get; private set; }
		public ILoanCenterService LoanCenterService { get; private set; }
		public ILoanProgramService LoanProgramService { get; private set; }
		public IStateService StateService { get; private set; }
        public ILoanSubmissionService LoanSubmissionService { get; private set; }

        public async Task<ActionResult> Index()
        {
            var currentUser = UserManager.FindById(User.Identity.GetUserId());
            

            return View();
        }

        [HttpGet]
        public ActionResult LoanInformation()
        {
            var currentUser = UserManager.FindById(User.Identity.GetUserId());
            currentUser.LeadStatus = "Started Application";
            UserManager.Update(currentUser);

            ViewBag.StateNames = StateService.GetStates().Select(s => s.Name);
			
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LoanInformation(LoanInformationViewModel model)
        {
            if (ModelState.IsValid)
            {
                LoanQualificationRestriction loanRestriction = (model.IsMedicalResident.HasValue && model.IsMedicalResident.Value) ?
                                                                        LoanQualificationRestriction.Residency :
                                                                        LoanQualificationRestriction.General;
                LoanProgram loanProgram = LoanProgramService.GetLoanProgram(model.StateOfResidence, model.LoanAmount, loanRestriction);

                // if the loan program is null than there is no program for that combination of state and loanrestriction
                if (loanProgram != null)
                {
                    if (model.LoanAmount > 15000 && model.LoanAmount < 450000)
                    {
                        var currentUser = UserManager.FindById(User.Identity.GetUserId());
                        currentUser.LeadStatus = "Left Portal";
                        UserManager.Update(currentUser);

                        LoanSubmissionService.SaveLoanSubmission(currentUser.Id, model.StateOfResidence, model.LoanAmount,
                            model.IsMedicalResident ?? false, loanProgram.Name, loanProgram.Url);

                        return ReturnLoanView(Web.Utilities.Configuration.CampusDoorNewLoanAppUrl + loanProgram.Url);
                    }
                    else
                    {
                        return View("NotAvailableLoanAmount");
                    }
                }
                else
                {
                    return View("NotAvailable");
                }
            }
            

            ViewBag.StateNames = StateService.GetStates().Select(s => s.Name);
            return View(model);
        }


        [HttpGet]
        public ActionResult CheckList()
        {
            return File("~/downlods/LinkCapital_Application_Checklist.pdf", "application/pdf", "LinkCapital_Application_Checklist.pdf");
        }

        private ViewResult ReturnLoanView(string url)
        {
            var currentUser = UserManager.FindById(User.Identity.GetUserId());

            var loanAppModel = new LoanApplicationViewModel();
            loanAppModel.HttpMethod = "POST";
            loanAppModel.Payload = LoanCenterService.GetCampusDoorToken(currentUser);
            loanAppModel.Url = url;

            return View("LoanApplication", loanAppModel);
        }

        /// <summary>Transfer to Campus Door's My Account</summary>
        /// <returns>Return</returns>
        [HttpGet]
        public ActionResult ContinueApplication()
        {
            var currentUser = UserManager.FindById(User.Identity.GetUserId());
            LoanApplicationViewModel viewModel = new LoanApplicationViewModel
            {
                HttpMethod = "POST",
                Payload = LoanCenterService.GetCampusDoorToken(currentUser),
                Url = Configuration.CampusDoorMyAccountUrl
            };

            return View("LoanApplication", viewModel);
        }

        [HttpGet]
        public ActionResult ManageLoan()
        {
            ManageLoanViewModel viewModel = new ManageLoanViewModel
            {
                HttpMethod = "Post",
                Payload = string.Empty,
                Url = "https://myaccount.studentloan.org"
            };

            return View("LoanManagementView", viewModel);
        }

        [HttpGet]
        public ActionResult NotAvailable()
        {
            return View();
        }
    }
}

LinkCapital.Portal/Web/Views/LoanCenter/Index.cshtml
@{
    ViewBag.Title = "Index";
    ViewBag.PageClassName = "loancenter";
}

<!--<div class="row @ViewBag.PageClassName">
    <section>
        <div class="col-md-5 col-md-offset-1">
            <div class="row col-12 loancenter-hdr">
                <h1 class="text-center">Apply for a Loan</h1>
                <p id="Instructions" class="text-center">Ready to start saving? Click the start button below to begin your new application or click continue to complete your existing application.</p>
            </div>
            <div class="row visible-xs col-xs-10 col-xs-offset-1 col-sm-12 col-sm-offset-0 col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2 loancenter-btns">
                <ul id="CampusDoorLinks" class="list-unstyled">
                    @*<li style="margin-bottom: 1em">@Html.ActionLink("Start Here", "LoanInformation", "LoanCenter", new { @class = "btn btn-loancenter btn-block" })</li><span class="glyphicon glyphicon-search" aria-hidden="true"></span>*@
                    <li style="margin-bottom: 1em"><a class="btn btn-loancenter btn-block" href="@Url.Action("LoanInformation", "LoanCenter")">Start Here <span class="glyphicon glyphicon-chevron-right" aria-hidden="false"></span></a></li>

                    <li style="margin-bottom: 1em">@Html.ActionLink("Continue Application", "ContinueApplication", "LoanCenter", new { @class = "btn btn-loancenter btn-block" })</li>
                </ul>
            </div>
        </div>
    </section>
    <section>
        <div class="col-md-5 col-md-offset-1">
            <div class="row col-12 loancenter-hdr">
                <h1 class="text-center">Loan Management</h1>
                <p id="InstructionsManage" class="text-center">To manage your loans, make a payment or see your account details, click the link below.</p>
                
                <div class="row visible-xs col-xs-10 col-xs-offset-1 col-sm-12 col-sm-offset-0 col-md-12 col-md-offset-1 col-lg-8 col-lg-offset-2 loancenter-btns">
                    <ul id="ApireLinks" class="list-unstyled">
                        @*<li style="margin-bottom: 1em"><a class="btn btn-loancenter btn-block" href="https://myaccount.studentloan.org">Manage My Loans <span class="glyphicon glyphicon-chevron-right" aria-hidden="false"></span></a></li>*@
                        <li style="margin-bottom: 1em"><a class="btn btn-loancenter btn-block" href="@Url.Action("ManageLoan", "LoanCenter")">Manage My Loans <span class="glyphicon glyphicon-chevron-right" aria-hidden="false"></span></a></li>
                    </ul>
                </div>
            </div>
        </div>
</section>
</div>

<div class="row">
    <section>
        <div class="col-md-5 col-md-offset-1">
            <div class="row hidden-xs col-xs-10 col-xs-offset-1 col-sm-12 col-sm-offset-0 col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2 loancenter-btns">
                <ul id="CampusDoorLinks" class="list-unstyled">
                    @*<li style="margin-bottom: 1em">@Html.ActionLink("Start Here", "LoanInformation", "LoanCenter", new { @class = "btn btn-loancenter btn-block" })</li><span class="glyphicon glyphicon-search" aria-hidden="true"></span>*@
                    <li style="margin-bottom: 1em"><a class="btn btn-loancenter btn-block" href="@Url.Action("LoanInformation", "LoanCenter")">Start Here <span class="glyphicon glyphicon-chevron-right" aria-hidden="false"></span></a></li>

                    <li style="margin-bottom: 1em">@Html.ActionLink("Continue Application", "ContinueApplication", "LoanCenter", new { @class = "btn btn-loancenter btn-block" })</li>
                </ul>
            </div>
        </div>
    </section>
    <section>
        <div class="col-md-5 col-md-offset-1">
            <div class="row col-12 loancenter-hdr">
                <div class="row hidden-xs col-xs-10 col-xs-offset-1 col-sm-12 col-sm-offset-0 col-md-12 col-md-offset-1 col-lg-8 col-lg-offset-2 loancenter-btns">
                    <ul id="ApireLinks" class="list-unstyled">
                        @*<li style="margin-bottom: 1em"><a class="btn btn-loancenter btn-block" href="https://myaccount.studentloan.org">Manage My Loans <span class="glyphicon glyphicon-chevron-right" aria-hidden="false"></span></a></li>*@
                        <li style="margin-bottom: 1em"><a class="btn btn-loancenter btn-block" href="@Url.Action("ManageLoan", "LoanCenter")">Manage My Loans <span class="glyphicon glyphicon-chevron-right" aria-hidden="false"></span></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
</div> -->

@*@section Scripts {
    <script>
        var clickCount = 0;
        function clickLink(link) {
            if (++clickCount >= 13) {
                $(link).hide();
                $("#Instructions").show();
                $("#CampusDoorLinks").show();
                $('#ApireLinks').show();
                $("#InstructionsManage").show();
            }
        }
    </script>*@
@*}*@

<div class="row text-center">
    <div class="col-sm-5 col-sm-offset-1">
        <h1>Apply for a Loan</h1>
        <p>Ready to start saving? Click the start button below to begin your new application or click continue to complete your existing application.</p>
        <div class="row visible-xs" style="padding-top:50px;">
            <a class=" btn btn-loancenter col-xs-12 small" style="margin-bottom:15px;" href="@Url.Action("LoanInformation", "LoanCenter")">
                Start Here <span class="glyphicon glyphicon-chevron-right" aria-hidden="false"></span>
            </a>
            <a class="btn btn-loancenter col-xs-12 small" href="@Url.Action("ContinueApplication", "LoanCenter")">Continue Application</a>
            <div style="padding-top:10px">
                What do you need to apply? 
                <a class="link-loancenter col-xs-12 small" href="@Url.Action("CheckList", "LoanCenter")"> Click here!</a>
            </div>
        </div>
    </div>
    <div class="col-sm-5 col-sm-offset-1">
        <h1>Loan Management</h1>
        <p>To manage your loans, make a payment or see your account details, click the link below.</p>
        <div class="row visible-xs" style="padding-top:50px;">
            <a class=" btn btn-loancenter col-xs-12 small" href="@Url.Action("ManageLoan", "LoanCenter")">
                Manage My Loans <span class="glyphicon glyphicon-chevron-right" aria-hidden="false"></span>
            </a>
        </div>
    </div>
</div>
<div class="row hidden-xs" style="padding-top:50px;">
    <div class=" col-sm-5 col-sm-offset-1 text-center">
    <div class="row">
        <a class="btn btn-loancenter col-xs-10 col-xs-offset-1 col-sm-12 col-sm-offset-0 col-md-12 col-md-offset-1 col-lg-8 col-lg-offset-2" style="margin-bottom:15px;" href="@Url.Action("LoanInformation", "LoanCenter")">Start Here <span class="glyphicon glyphicon-chevron-right" aria-hidden="false"></span></a>
        <a class="btn btn-loancenter col-xs-10 col-xs-offset-1 col-sm-12 col-sm-offset-0 col-md-12 col-md-offset-1 col-lg-8 col-lg-offset-2" href="@Url.Action("ContinueApplication", "LoanCenter")">Continue Application</a>
        <div class="col-xs-10 col-xs-offset-1 col-sm-12 col-sm-offset-0 col-md-12 col-md-offset-1 col-lg-8 col-lg-offset-2" style="padding-top:10px">
            What do you need to apply?
            <a class="link-loancenter col-xs-10 col-xs-offset-1 col-sm-12 col-sm-offset-0 col-md-12 col-md-offset-1 col-lg-8 col-lg-offset-2" href="@Url.Action("CheckList", "LoanCenter")">Click here!</a>
        </div>
    </div>
</div>
    <div class="col-sm-5 col-sm-offset-1 text-center">
        <div class="row">
            <a class="btn btn-loancenter col-xs-10 col-xs-offset-1 col-sm-12 col-sm-offset-0 col-md-12 col-md-offset-1 col-lg-8 col-lg-offset-2" href="@Url.Action("ManageLoan", "LoanCenter")">Manage My Loans <span class="glyphicon glyphicon-chevron-right" aria-hidden="false"></span></a>
        </div>
    </div>
</div>

LinkCapital.Portal/Web/Views/LoanCenter/LoanApplication.cshtml
@model Web.ViewModels.LoanCenter.LoanApplicationViewModel
@{
    ViewBag.Title = "Loan Application";
}

<header>
</header>

<div class="row">
    <div class="col-md-12">
        <span>Redirecting to Loan Application Service...</span>
        <form id="loanAppForm" action="@Model.Url" method="@Model.HttpMethod">
            @Html.Hidden("payload", @Model.Payload)
        </form>
    </div>
</div>

@section Scripts {
    <script type="text/javascript">
    $(document).ready(function () {
        $('#loanAppForm').submit();
    });
    </script>
}

LinkCapital.Portal/Web/Views/LoanCenter/LoanInformation.cshtml
@model Web.ViewModels.LoanCenter.LoanInformationViewModel
@{
    ViewBag.Title = "Your Loan Application";
}

<header>
    <h1 class="Application_Header">Your Loan Application</h1>
    <!--[if lte IE 9]>
    <style>
        .hidden { display:block !important; visibility:visible !important }
    </style>
    <![endif]-->

</header>

<!-- Modal -->
<div class="modal fade" id="residencyModal" tabindex="-1" role="dialog" data-backdrop="false" aria-labelledby="residencyModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="residencyModalLabel">Confirm - Medical Residency/Fellowship</h4>
            </div>
            <div class="modal-body">
                You have indicated that you are a medical resident or fellow. During the application process, you will be required to provide proof of your residency/fellowship.
                When asked to enter our income, please use the income you expect to make after you training period is complete, not your current income.
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button id="residencyModalContinueButton" type="button" class="btn btn-primary">Continue</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="consolidationModal" tabindex="-1" role="dialog" data-backdrop="false" aria-labelledby="consolidationModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="consolidationModalLabel">Confirm - Immediate Loan Consolidation</h4>
            </div>
            <div class="modal-body">
                You have selected an immediate repayment consolidation loan intended for medical professionals who are not currently in a training program. If you are a resident
                or fellow and looking for the ability to defer your loan during training, please select yes to the question “Are you a medical resident or fellow?” to be directed
                to the correct option. 
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button id="consolidationModalContinueButton" type="button" class="btn btn-primary">Continue</button>
            </div>
        </div>
    </div>
</div>

@using (Html.BeginForm("LoanInformation", "LoanCenter", FormMethod.Post, new { role = "form", id="loanForm" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary("", new { @class = "text-danger" })

            <div class="row">
                <div class="form-group col-md-6">
                    @Html.LabelFor(m => m.StateOfResidence, new { @class = "control-label hidden" })
                    @Html.DropDownListFor(m => m.StateOfResidence, new SelectList(ViewBag.StateNames), "Permanent Residence", new { @class = "form-control input-lg", onchange = "selectState(this)" })
                </div>
                <div class="form-group col-md-6">
                    @Html.LabelFor(m => m.LoanAmount, new { @class = "control-label hidden" })
                    <div class="input-group">
                        <span class="input-group-addon">$</span>
                        @Html.TextBoxFor(m => m.LoanAmount, new { @class = "form-control input-lg", placeholder = @Html.DisplayNameFor(o => o.LoanAmount) })
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-12">
                    <span>Are You a Medical Resident or Fellow?</span>
                    @Html.ValidationMessageFor(x => x.IsMedicalResident, "*")
                    <a id="residencyPopover" class="inline-help" href="#" tabindex="0" role="button" data-toggle="popover" data-trigger="focus" title="Medical Residency" data-content="Only answer yes if you are currently in a medical residency program.">
                        @*<img src="~/Content/Images/help_icon.png" alt="Help" />*@
                        <div class="glyphicon glyphicon-question-sign"></div>
                    </a>
                </div>
            </div>
            <div class="row">
                <div class="lc-radio-item col-md-2">
                    <label for="residency_yes">
                        @Html.RadioButtonFor(x => x.IsMedicalResident, "true", new { id = "residency_yes" })
                        <span></span>
                        <span>YES</span>
                    </label>
                </div>
                <div class="lc-radio-item col-md-2">
                    <label for="residency_no">
                        @Html.RadioButtonFor(x => x.IsMedicalResident, "false", new { id = "residency_no" })
                        <span></span>
                        <span>NO</span>
                    </label>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-offset-9 col-md-3">
                    <input id="submitButton" type="submit" value="Next" class="btn btn-default btn-block" />
                </div>
            </div>
        }

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        function selectState(select)
        {
            select.style.color = "black";
            $(select).children("option:first-child").attr("disabled", "disabled");
        }

        $(document).ready(function() {
            $('#residencyPopover').popover();

            $('#submitButton').click(function() {
                if ($('input[name=IsMedicalResident]:checked').val() === "true") {
                    $('#residencyModal').appendTo("body").modal('show');
                    return false;
                }

                if ($('input[name=IsMedicalResident]:checked').val() === "false") {
                    $('#consolidationModal').appendTo("body").modal('show');
                    return false;
                }

                $('#residencyModal').modal('hide');
                $('#consolidationModal').modal('hide');
                return true;
            });

            $('#residencyModalContinueButton').click(function () {
                $('#residencyModal').modal('hide');
                $('#loanForm').submit();
            });

            $('#consolidationModalContinueButton').click(function () {
                $('#consolidationModal').modal('hide');
                $('#loanForm').submit();
            });
        });
    </script>
}

LinkCapital.Portal/Web/Views/LoanCenter/LoanManagementView.cshtml
@model Web.ViewModels.LoanCenter.ManageLoanViewModel
@{
    ViewBag.Title = "Loan Management";
}

<header></header>

<div class="row">
    <div class="col-md-12">
        <span>Redirecting to Loan Management Service...</span>
        <form id="loanManageForm" action="@Model.Url" method="@Model.HttpMethod">
            @Html.Hidden("payload", @Model.Payload)
        </form>
    </div>
</div>

@section Scripts {
    <script type="text/javascript">
    $(document).ready(function () {
        $('#loanManageForm').submit();
    });
    </script>
}

LinkCapital.Portal/Web/Views/LoanCenter/NotAvailable.cshtml
@{
    ViewBag.Title = "Please Check Back";
}

<header>
    <!-- <h1 class="Application_Header">No Programs Available</h1> -->
</header>

<div>
    <p>Link Capital is currently only offering loans to residents in certain states.  We plan to widen our offering within the next couple of weeks.  
        Please check back again soon or contact us directly at <a href="mailto:info@linkcapital.com">info@linkcapital.com</a>.</p>
</div>

LinkCapital.Portal/Web/Views/LoanCenter/NotAvailableLoanAmount.cshtml
@{
    ViewBag.Title = "Please Check Back";
}

<header>
    <!-- <h1 class="Application_Header">No Programs Available</h1> -->
</header>

<div>
    <p>The Consolidation Loan Program has a minimum loan amount of $15,000 and a maximum loan amount of $450,000. Note that there is no minimum or maximum 
    limit on the outstanding balance of any individual loan to be consolidated but all loans to be consolidated must total at least $15,000.
    </p>
</div>